logging:
    file: application.log

memcache:
    servers:
        - 127.0.0.1

oAuth:
    twitter:
        key: *********
        secret: *********

mongodb:
    database: saucer
    server:
        host: localhost
        port: 27017
